/**
 * Stable - Auth Service
 * An authentication service API for Stable
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConfirmRequestDto { 
    /**
     * The email of the user
     */
    email: string;
    /**
     * The confirmation code sent to the user\'s email
     */
    code: string;
}

